passwd:		compat
group:		compat
shadow:		compat

hosts:		dns [!UNAVAIL=return] files
networks:	nis [NOTFOUND=return] files
ethers:		nis [NOTFOUND=return] files
protocols:	nis [NOTFOUND=return] files
rpc:		nis [NOTFOUND=return] files
services:	nis [NOTFOUND=return] files
